apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dgb-idt-jkns14-home-rbd
  namespace: dgb-ny2np2-jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: dynamicfiles
  volumeMode: Filesystem








# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: dgb-idt-jkns14-home-rbd
#   namespace: dgb-ny2np2-jenkins
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: ceph-rbd-storage
#   volumeMode: Filesystem