# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: dgb-ny2np2-jnks-svc-acc
#   namespace: dgb-ny2np2-jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: Jenkins_Controller_permissions
  namespace: dgb-ny2np2-jenkins
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
      - pods/log
      - pods/attach
      - secrets
      - configmaps
      - services
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dgb-idt-jkns14-RoleBinding
  namespace: dgb-ny2np2-jenkins
subjects:
  - kind: ServiceAccount
    name: dgb-ny2np2-jnks-svc-acc
    namespace: dgb-ny2np2-jenkins
roleRef:
  kind: Role
  name: Jenkins_Controller_permissions
  apiGroup: rbac.authorization.k8s.io