apiVersion: v1
kind: Secret
metadata:
  name: agent-1-secret
  namespace: dgb-ny2np2-jenkins
type: Opaque
stringData:
  JENKINS_SECRET: "37f2b2cabef46567ec5cdbcdd1d1cf0bd6aaa220681e00e96ec25ec9ce587574"
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-2-secret
  namespace: dgb-ny2np2-jenkins
type: Opaque
stringData:
  JENKINS_SECRET: "f66fc474eb765935ce502cab3da2fe0a37cd68fd6d4fee42cbea41d8c3faa9f1"
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: agent-3-secret
#   namespace: jenkins
# type: Opaque
# stringData:
#   JENKINS_SECRET: "83aded109131766f7956d1660a8ba39ab08bd6b5eb422ccec4d91337fd1f3a9a"